### ISSUE TITLE
Install from elasticsearch plugin repository

### ISSUE THREAD

**Issue by gsouf** [uschindler/es-legacy-completion-plugin#1]
Hi,

Is it possible to install this plugin with the method ``bin/elastisearch-plugin install ....`` ?

If it's not possible, can you ggive further details on how to actually install it please?
I'm not a java developer I dont know much about the solution you give in the readme. I presume that ``mvn`` stands for maven?

Thank you

**Comment by gsouf** [comment]
Well, java world was not as frightening as in my remember of a child playing with computers.

I managed to install it with maven, but it would be very good if the plugin can be installed from the elasticsearch plugin manager. Especially because this features is very useful.

**Comment by uschindler** [comment]
Hi,
I changed the plugin to POM file to create a ZIP file that can be installed using the Elasticsearch plugin manager command in commit 71b3c2f68fda5d25b78ea7802382be55b162e754. I updated the docs accordingly.

**Comment by uschindler** [comment]
You still have to build the plugin yourself with Maven, but because I do not want to maintain a separate ZIP file for every Elasticsearch version out there, I only provide the 5.3.0 version here (and a branch with latest 5.2.1, because there is a small code change needed).

**Comment by gsouf** [comment]
Thanks!
