### ISSUE TITLE
Is Context based filtering supported ?

### ISSUE THREAD

**Issue by muralikg** [uschindler/es-legacy-completion-plugin#3]
Hi @uschindler ,

Thanks for the plugin. It is very useful.
I wanted to know if the results can be filtered based on context provided. I tried testing it but did not get back any results.

```
client.indices.putMapping({
	index: 'issues',
	type: 'exception',
	body: {
		properties: {
			browser: {
				type: 'text',
				fields: {
					raw: {type: 'keyword'},
					suggest: {
						type: "legacy_completion",
						context: {
							os: { 
								type: "category",
								path: 'os',
							}
						}
					}
				}
			},
			os: {
				type: "keyword",
			}
		}
	}
})


client.index({
	index: 'issues',
	type: 'exception',
	id: 1,
	body: {
		browser: 'chrome 60',
		os: 'ubuntu',
	}
})

client.suggest({
	index: 'issues',
	body: {
		browser: {
			text: 'chrom',
			completion: {
				field: 'browser.suggest',
				context: {
					os: ['ubuntu']
				}
			}
		}
	}
}).then(console.log)
```

The query above returns no results back. Although it works perfectly fine when used without context.
Am I configuring it wrong?

**Comment by uschindler** [comment]
Hi,

sorry I never used the context filtering. If it was available in old version of ES 2.x, it should still work, but that's up to Elasticsearch's backwards compatibility. The plugin just allows to create legacy completion fields, but it does not handle querying them. This is done by upstream Elasticsearch.
