### ISSUE TITLE
elasticsearch 6

### ISSUE THREAD

**Issue by afrozl** [uschindler/es-legacy-completion-plugin#5]
I realize this is an unsupported 'hack', but I do need the functionality this plugin provides for auto-completion of tagging. I would rather not go the route of adding a separate index, so does this still work with elasticsearch 6?

**Comment by uschindler** [comment]
I don't think you can use it with Elasticsearch 6, but I have not yet tried to compile it. If you change the maven POM to use ES 6 and recompile and it builds fine, it should work.

I can test it for you, but as far as I remember the classes and support for ES 2.x indexes is gone in recent Elasticsearch.

**Comment by afrozl** [comment]
I can test it. It really is a shame because I actually have need for both types of suggesters. Each user in my app has their own index for saved documents and needs the ES 2,x suggester for tagging the docs based on existing tags within saved docs. The new suggester would work great in terms of suggesting documents to discover and/or save into the user index.

**Comment by afrozl** [comment]
Looks like it won't work...
<pre>
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /elasticsearch/apps/es-legacy-completion-plugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /elasticsearch/apps/es-legacy-completion-plugin/src/main/java/de/thetaphi/elasticsearch/suggest/LegacyCompletionFieldMapper.java:[38,38] cannot find symbol
  symbol:   class CompletionFieldMapper2x
  location: package org.elasticsearch.index.mapper
[ERROR] /elasticsearch/apps/es-legacy-completion-plugin/src/main/java/de/thetaphi/elasticsearch/suggest/LegacyCompletionFieldMapper.java:[43,53] package org.elasticsearch.search.suggest.completion2x does not exist
</pre>

**Comment by uschindler** [comment]
Thanks for feedback. There is nothing we can do. I am stuck with ES 5.6.x at the moment, too.
